### ISSUE TITLE
path seems to be broken in the caseStudyWP

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/SalmonLRP_csasdown#1]
I think that here is referencng the root  directory, so that the paths need to be adjusted for the caseStudyWP folder. --I could implement that fix, but I want to make sure I won't break anything by doing that. 

Here is the error that I am getting: 
SalmonLRP_csasdown/R/make_tree_diagram.R :  No such file or directory

I believe that the path to the figure should be:
source(here::here("caseStudyWP/R/make_tree_diagram.R"))

**Comment by lukewarkentin** [comment]
I was getting errors with the here::here("caseStudyWP... path referencing. I removed the here:here() argument and just started each path with figures/ or R/ and left out the caseStudyWP/ folder, and all seems to be working.

**Comment by catarinawor** [comment]
Thanks for checking into this, Luke. Everything is working for me now.
